apiVersion: apps/v1
kind: Deployment
metadata:
  name: context-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: context-service
  template:
    metadata:
      labels:
        app: context-service
    spec:
      containers:
        - name: context-service
          image: estrella1708/context-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_APPLICATION_NAME
              value: "context-service"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          ports:
            - containerPort: 8089
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: context-service
spec:
  selector:
    app: context-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP