apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-service
  template:
    metadata:
      labels:
        app: news-service
    spec:
      containers:
        - name: news-service
          image: estrella1708/news-service:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_APPLICATION_NAME
              value: "NewsSourceApplication"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: EUREKA_INSTANCE_PREFER_IP_ADDRESS
              value: "true"
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: news-service
spec:
  selector:
    app: news-service
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  type: ClusterIP